Report properly optional arguments that are missing a value
Before:

  $ Jucer2CMake.exe reprojucer NewProject/NewProject.jucer --juce-modules
  error: unknown option "juce-modules"
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]

After:

  $ Jucer2CMake.exe reprojucer NewProject/NewProject.jucer --juce-modules
  error: expected one argument for "juce-modules"
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]