Report invalid "mode" argument first
"mode" is the first positional argument, so it should be fixed first
before adding more.

Before:

  $ Jucer2CMake whatever
  error: not enough positional arguments
  error: invalid mode "whatever"
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]

After:

  $ Jucer2CMake whatever
  error: invalid mode "whatever"
  error: not enough positional arguments
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]