Change hard-coded 'reprojucer' to actual "mode" argument
In a subsequent commit, we will introduce another mode: 'juce6'.

Before:

  $ Jucer2CMake
  error: not enough positional arguments
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [--help] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]

  $ Jucer2CMake -h
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [--help] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]

  Converts a .jucer file into a CMakeLists.txt file that uses Reprojucer.cmake.
  The CMakeLists.txt file is written in the current working directory.

      <jucer_project_file>      path to the .jucer file to convert
      <Reprojucer.cmake_file>   path to Reprojucer.cmake

      -h, --help                show this help message and exit
      --juce-modules <path>     global path to JUCE modules
      --user-modules <path>     global path to user modules
      --relocatable             makes the CMakeLists.txt file independent from
                                the location of the .jucer file, but requires
                                defining a variable when calling cmake

After:

  $ Jucer2CMake
  error: not enough positional arguments
  usage: Jucer2CMake {reprojucer} <jucer_project_file> [--help] [<args>]

  $ Jucer2CMake -h
  usage: Jucer2CMake <mode> <jucer_project_file> [--help] [<args>]

  Converts a .jucer file into a CMakeLists.txt file.
  The CMakeLists.txt file is written in the current working directory.

      <mode>                    what the generated CMakeLists.txt uses:
        reprojucer                - FRUT's Reprojucer

      <jucer_project_file>      path to the .jucer file to convert

      -h, --help                show this help message and exit

The diff of this commit is easier to read when ignoring whitespace
changes. To do so in GitHub, append "?w=1" to the URL.