Fix building IconBuilder when using latest VS2019 (16.10+)
Otherwise, building IconBuilder fails with:

  JUCE\modules\juce_gui_basics\juce_gui_basics.cpp : fatal error C1128:
  number of sections exceeded object file format limit: compile with
  /bigobj

This was not caught on CI because the Azure Pipelines VMs have VS2019
version 16.9.31229.75 installed [1].

[1]: https://github.com/actions/virtual-environments/blob/win19/20210516.0/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019