Fix occasional linker failures on Travis CI
These failures occur when we test FRUT using the "Unix Makefiles"
generator on the "xcode7.3" image of Travis CI. When configuring in
"ci/AllJuceProjects/Debug_build" for the first time, Reprojucer
configures, builds, and installs BinaryDataBuilder, then configures and
builds IconBuilder, which fails with:

  Undefined symbols for architecture x86_64:
    "juce::this_will_fail_to_link_if_some_of_your_compile_units_are_buil
t_in_release_mode::this_will_fail_to_link_if_some_of_your_compile_units_
are_built_in_release_mode()", referenced from:
        ___cxx_global_var_init in libtools_juce_gui_basics.a(juce_gui_ba
sics.mm.o)
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see in
vocation)

These failures are due to the sum of 3 bugs/unexpected behaviors:
1. CMAKE_BUILD_TYPE is initially not set to "Debug" when we configure,
build, and install BinaryDataBuilder
2. the static library tools_juce_gui_basics is built when installing
BinaryDataBuilder
3. make (or CMake) sometimes doesn't detect that some files need to be
re-built

To understand 1., I made the following CMakeLists.txt file:

  if(DEFINED CMAKE_BUILD_TYPE)
    message("CMAKE_BUILD_TYPE is defined: *${CMAKE_BUILD_TYPE}*")
  else()
    message("CMAKE_BUILD_TYPE is NOT defined")
  endif()

  if(NOT DEFINED CMAKE_CONFIGURATION_TYPES)
    if(NOT DEFINED CMAKE_BUILD_TYPE OR CMAKE_BUILD_TYPE STREQUAL "")
      message("Setting CMAKE_BUILD_TYPE to \"Debug\" as it was not specified.")
      set(CMAKE_BUILD_TYPE Debug)
    endif()
  endif()

  if(DEFINED CMAKE_BUILD_TYPE)
    message("CMAKE_BUILD_TYPE is defined: *${CMAKE_BUILD_TYPE}*")
  else()
    message("CMAKE_BUILD_TYPE is NOT defined")
  endif()

  message("Before project()")
  project(test)
  message("After project()")

  if(DEFINED CMAKE_BUILD_TYPE)
    message("CMAKE_BUILD_TYPE is defined: *${CMAKE_BUILD_TYPE}*")
  else()
    message("CMAKE_BUILD_TYPE is NOT defined")
  endif()

then configured it twice on the "xcode7.3" image of Travis CI:

  $ cmake ..
  CMAKE_BUILD_TYPE is NOT defined
  Setting CMAKE_BUILD_TYPE to "Debug" as it was not specified.
  CMAKE_BUILD_TYPE is defined: *Debug*
  Before project()
  -- The C compiler identification is AppleClang 7.3.0.7030031
  -- The CXX compiler identification is AppleClang 7.3.0.7030031
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
  -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++
  -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  After project()
  CMAKE_BUILD_TYPE is defined: **
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /Users/travis/build/McMartin/FRUT/build
  The command "cmake .." exited with 0.

  $ cmake ..
  CMAKE_BUILD_TYPE is defined: **
  Setting CMAKE_BUILD_TYPE to "Debug" as it was not specified.
  CMAKE_BUILD_TYPE is defined: *Debug*
  Before project()
  After project()
  CMAKE_BUILD_TYPE is defined: *Debug*
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /Users/travis/build/McMartin/FRUT/build
  The command "cmake .." exited with 0.

As we can see, calling `project(tools)` during the initial configure
overrides CMAKE_BUILD_TYPE and sets it to the empty string. This would
lead to the first tool built by Reprojucer (usually BinaryDataBuilder)
being compiled with -DNDEBUG=1 and the next ones being compiled with
-DDEBUG=1. This commit fixes this bug/unexpected behavior.

Because of 2., libtools_juce_gui_basics.a was first built with
-DNDEBUG=1 when installing BinaryDataBuilder. The next commit fixes that
bug.

Because of 3., libtools_juce_gui_basics.a would sometimes not be
re-built, though the preprocessor defines had changed, and the linker
would fail.