Adapt to updated Ubuntu Trusty images on Travis CI
The package libgl1-mesa-dev was removed from the images and this leads
to the following failure:

  /home/travis/build/McMartin/JUCE/modules/juce_opengl/juce_opengl.h:90:20:
  fatal error: GL/gl.h: No such file or directory
    #include <GL/gl.h>
                    ^
  compilation terminated.