Don't report missing "mode" argument as invalid
It's redundant and only adds noise to the output.

Before:

  $ Jucer2CMake
  error: not enough positional arguments
  error: invalid mode ""
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]

After:

  $ Jucer2CMake
  error: not enough positional arguments
  usage: Jucer2CMake reprojucer <jucer_project_file> [<Reprojucer.cmake_file>]
                     [-h] [--juce-modules=<path>] [--user-modules=<path>]
                     [--relocatable]